services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: supermarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./products_list.csv:/docker-entrypoint-initdb.d/products_list.csv
      - ./purchases.csv:/docker-entrypoint-initdb.d/purchases.csv

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    

  app_a:
    build:
      context: ./app_a
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: supermarket
    ports:
      - "8000:8000"
  

  app_b:
    build:
      context: ./app_b
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: supermarket
    ports:
      - "8001:8001"

volumes:
  db_data: